### ISSUE TITLE
Suppress required for edit option to be available

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/exhibits-backend#3]
Can not edit or view data if the exhibit or item is published.

If an exhibit is live, and base template needs editing, must go offline (supressed) first. exhibit should be editable any time.

Request: to confirm that live/published exhibits or items will be changed when they go live, instead of having to unpublish items/exhibit first to edit them

**Comment by freyesdulib** [comment]
Will address this enhancement request with enhancement #17
