### ISSUE TITLE
Reordering one grid item automatically publishes the grid and all of the items in the grid

### ISSUE THREAD

**Issue by jrynhart** [dulibrarytech/exhibits-backend#31]
After reordering a grid item, all of the grid items are published. Need to exit the grid and unpublish it, then go back in if more items are to be reordered. Extra step if reordering >1 grid item

**Comment by freyesdulib** [comment]
Staff likely won't do a massive reorder after an exhibit is published.  If a complete reorder of items is required, then it's best to unpublish the entire exhibit to do so.  We'll get more clarity on this type of process when exhibit staff and UI/EX person begins testing.
